"""Regenerate Pydantic and TypeScript types from the canonical event schema.

Usage:
    uv run python packages/schemas/scripts/codegen.py          # regenerate in place
    uv run python packages/schemas/scripts/codegen.py --check  # CI drift check, exit 1 on diff

Never hand-edit the generated files.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
SCHEMA = PKG / "schema" / "event.schema.json"
PY_OUT = PKG / "src" / "abx_schemas" / "generated" / "event.py"
TS_OUT = PKG / "generated" / "event.ts"

HEADER = "# Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"
TS_HEADER = "// Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"


def gen_python(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input", str(SCHEMA),
            "--input-file-type", "jsonschema",
            "--output", str(out),
            "--output-model-type", "pydantic_v2.BaseModel",
            "--target-python-version", "3.12",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-annotated",
            "--collapse-root-models",
            "--disable-timestamp",
            "--use-schema-description",
            "--class-name", "CanonicalEvent",
        ],
        check=True,
    )
    out.write_text(HEADER + out.read_text(encoding="utf-8"), encoding="utf-8")
    init = out.parent / "__init__.py"
    if not init.exists():
        init.write_text(HEADER, encoding="utf-8")


def gen_typescript(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "pnpm", "dlx", "json-schema-to-typescript",
            str(SCHEMA),
            "--bannerComment", "",
            "--additionalProperties", "false",
        ],
        check=True,
        capture_output=True,
        text=True,
        shell=(sys.platform == "win32"),
    )
    out.write_text(TS_HEADER + result.stdout, encoding="utf-8")


def main() -> int:
    check = "--check" in sys.argv
    if not check:
        gen_python(PY_OUT)
        gen_typescript(TS_OUT)
        print(f"wrote {PY_OUT}\nwrote {TS_OUT}")
        return 0

    with tempfile.TemporaryDirectory() as td:
        tmp_py = Path(td) / "event.py"
        tmp_ts = Path(td) / "event.ts"
        gen_python(tmp_py)
        gen_typescript(tmp_ts)
        drift = []
        if tmp_py.read_text(encoding="utf-8") != PY_OUT.read_text(encoding="utf-8"):
            drift.append(str(PY_OUT))
        if tmp_ts.read_text(encoding="utf-8") != TS_OUT.read_text(encoding="utf-8"):
            drift.append(str(TS_OUT))
        if drift:
            print(f"DRIFT: stale generated types: {drift}. Run codegen.py.", file=sys.stderr)
            return 1
        print("generated types match schema")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
