"""Regenerate Pydantic and TypeScript types from the schemas in schema/.

Usage:
    uv run python packages/schemas/scripts/codegen.py          # regenerate in place
    uv run python packages/schemas/scripts/codegen.py --check  # CI drift check, exit 1 on diff

Never hand-edit the generated files.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
SCHEMA_DIR = PKG / "schema"
PY_OUT_DIR = PKG / "src" / "abx_schemas" / "generated"
TS_OUT_DIR = PKG / "generated"

HEADER = "# Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"
TS_HEADER = "// Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"


def gen_python(schema: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input", str(schema),
            "--input-file-type", "jsonschema",
            "--output", str(out),
            "--output-model-type", "pydantic_v2.BaseModel",
            "--target-python-version", "3.12",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-annotated",
            "--collapse-root-models",
            "--disable-timestamp",
            "--use-schema-description",
        ],
        check=True,
    )
    out.write_text(HEADER + out.read_text(encoding="utf-8"), encoding="utf-8")
    init = out.parent / "__init__.py"
    if not init.exists():
        init.write_text(HEADER, encoding="utf-8")


def gen_typescript(schema: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "pnpm", "dlx", "json-schema-to-typescript",
            str(schema),
            "--bannerComment", "",
            "--additionalProperties", "false",
        ],
        check=True,
        capture_output=True,
        text=True,
        shell=(sys.platform == "win32"),
    )
    out.write_text(TS_HEADER + result.stdout, encoding="utf-8")


def generate_all(py_dir: Path, ts_dir: Path) -> list[tuple[Path, Path]]:
    """Generate all schemas into the given dirs; return (py, ts) paths per schema."""
    outputs = []
    for schema in sorted(SCHEMA_DIR.glob("*.schema.json")):
        stem = schema.name.removesuffix(".schema.json")
        py_out = py_dir / f"{stem}.py"
        ts_out = ts_dir / f"{stem}.ts"
        gen_python(schema, py_out)
        gen_typescript(schema, ts_out)
        outputs.append((py_out, ts_out))
    return outputs


def main() -> int:
    if "--check" not in sys.argv:
        for py_out, ts_out in generate_all(PY_OUT_DIR, TS_OUT_DIR):
            print(f"wrote {py_out}\nwrote {ts_out}")
        return 0

    with tempfile.TemporaryDirectory() as td:
        drift = []
        for tmp_py, tmp_ts in generate_all(Path(td) / "py", Path(td) / "ts"):
            real_py = PY_OUT_DIR / tmp_py.name
            real_ts = TS_OUT_DIR / tmp_ts.name
            for tmp, real in ((tmp_py, real_py), (tmp_ts, real_ts)):
                if not real.exists() or tmp.read_text(encoding="utf-8") != real.read_text(
                    encoding="utf-8"
                ):
                    drift.append(str(real))
        if drift:
            print(f"DRIFT: stale generated types: {drift}. Run codegen.py.", file=sys.stderr)
            return 1
        print("generated types match schemas")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
