"""Regenerate Pydantic and TypeScript types from the schemas in schema/.

Usage:
    uv run python packages/schemas/scripts/codegen.py          # regenerate in place
    uv run python packages/schemas/scripts/codegen.py --check  # CI drift check, exit 1 on diff

Never hand-edit the generated files.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
SCHEMA_DIR = PKG / "schema"
PY_OUT_DIR = PKG / "src" / "abx_schemas" / "generated"
TS_OUT_DIR = PKG / "generated"
CONTRACT_OUT = PY_OUT_DIR / "contract.py"
VERIFIER = PKG.parents[1] / "tools" / "abx_verify.py"

HEADER = "# Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"
TS_HEADER = "// Generated by packages/schemas/scripts/codegen.py. DO NOT EDIT.\n"
CONTRACT_BEGIN = "# BEGIN GENERATED HASHED FIELDS"
CONTRACT_END = "# END GENERATED HASHED FIELDS"


def hashed_fields() -> list[str]:
    document = json.loads((SCHEMA_DIR / "event.schema.json").read_text(encoding="utf-8"))
    fields = document.get("x-abx-hashed-fields")
    if not isinstance(fields, list) or not all(isinstance(field, str) for field in fields):
        raise RuntimeError("event schema must define x-abx-hashed-fields")
    return fields


def contract_source(fields: list[str]) -> str:
    lines = "\n".join(f'    "{field}",' for field in fields)
    return HEADER + f"HASHED_FIELDS: tuple[str, ...] = (\n{lines}\n)\n"


def verifier_source(source: str, fields: list[str]) -> str:
    start = source.index(CONTRACT_BEGIN)
    end = source.index(CONTRACT_END, start) + len(CONTRACT_END)
    lines = "\n".join(f'    "{field}",' for field in fields)
    block = f"{CONTRACT_BEGIN}\nHASHED_FIELDS = [\n{lines}\n]\n{CONTRACT_END}"
    return source[:start] + block + source[end:]


def gen_python(schema: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input", str(schema),
            "--input-file-type", "jsonschema",
            "--output", str(out),
            "--output-model-type", "pydantic_v2.BaseModel",
            "--target-python-version", "3.12",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-annotated",
            "--collapse-root-models",
            "--disable-timestamp",
            "--use-schema-description",
        ],
        check=True,
    )
    out.write_text(HEADER + out.read_text(encoding="utf-8"), encoding="utf-8")
    init = out.parent / "__init__.py"
    if not init.exists():
        init.write_text(HEADER, encoding="utf-8")


def gen_typescript(schema: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "pnpm", "dlx", "json-schema-to-typescript",
            str(schema),
            "--bannerComment", "",
            "--additionalProperties", "false",
        ],
        check=True,
        capture_output=True,
        text=True,
        shell=(sys.platform == "win32"),
    )
    out.write_text(TS_HEADER + result.stdout, encoding="utf-8")


def resolved_schema(schema: Path, destination: Path) -> Path:
    """Inline the canonical event contract for generators that reject modular refs."""
    if schema.name != "evidence.schema.json":
        return schema
    document = json.loads(schema.read_text(encoding="utf-8"))
    event = json.loads((SCHEMA_DIR / "event.schema.json").read_text(encoding="utf-8"))
    for key in ("$schema", "$id", "x-abx-hashed-fields"):
        event.pop(key, None)
    document.setdefault("$defs", {})["CanonicalEvent"] = event

    def replace_external_ref(value: object) -> None:
        if isinstance(value, dict):
            if value.get("$ref") == "event.schema.json":
                value["$ref"] = "#/$defs/CanonicalEvent"
            for child in value.values():
                replace_external_ref(child)
        elif isinstance(value, list):
            for child in value:
                replace_external_ref(child)

    replace_external_ref(document)
    destination.write_text(json.dumps(document), encoding="utf-8")
    return destination


def generate_all(py_dir: Path, ts_dir: Path) -> list[tuple[Path, Path]]:
    """Generate all schemas into the given dirs; return (py, ts) paths per schema."""
    outputs = []
    with tempfile.TemporaryDirectory() as td:
        for schema in sorted(SCHEMA_DIR.glob("*.schema.json")):
            stem = schema.name.removesuffix(".schema.json")
            py_out = py_dir / f"{stem}.py"
            ts_out = ts_dir / f"{stem}.ts"
            input_schema = resolved_schema(schema, Path(td) / schema.name)
            gen_python(input_schema, py_out)
            gen_typescript(input_schema, ts_out)
            outputs.append((py_out, ts_out))
    return outputs


def main() -> int:
    if "--check" not in sys.argv:
        for py_out, ts_out in generate_all(PY_OUT_DIR, TS_OUT_DIR):
            print(f"wrote {py_out}\nwrote {ts_out}")
        fields = hashed_fields()
        CONTRACT_OUT.write_text(contract_source(fields), encoding="utf-8")
        VERIFIER.write_text(
            verifier_source(VERIFIER.read_text(encoding="utf-8"), fields),
            encoding="utf-8",
        )
        print(f"wrote {CONTRACT_OUT}\nupdated {VERIFIER}")
        return 0

    with tempfile.TemporaryDirectory() as td:
        drift = []
        for tmp_py, tmp_ts in generate_all(Path(td) / "py", Path(td) / "ts"):
            real_py = PY_OUT_DIR / tmp_py.name
            real_ts = TS_OUT_DIR / tmp_ts.name
            for tmp, real in ((tmp_py, real_py), (tmp_ts, real_ts)):
                if not real.exists() or tmp.read_text(encoding="utf-8") != real.read_text(
                    encoding="utf-8"
                ):
                    drift.append(str(real))
        if drift:
            print(f"DRIFT: stale generated types: {drift}. Run codegen.py.", file=sys.stderr)
            return 1
        fields = hashed_fields()
        if not CONTRACT_OUT.exists() or CONTRACT_OUT.read_text(
            encoding="utf-8"
        ) != contract_source(fields):
            print(f"DRIFT: stale generated contract: {CONTRACT_OUT}", file=sys.stderr)
            return 1
        verifier = VERIFIER.read_text(encoding="utf-8")
        if verifier != verifier_source(verifier, fields):
            print(f"DRIFT: stale verifier contract: {VERIFIER}", file=sys.stderr)
            return 1
        print("generated types match schemas")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
