import Link from "next/link";
import { ErrorState, PageHeader, Panel, SeverityBadge } from "@/components/ui";
import { apiGet, formatDate, humanize, type Alert, type AlertChannel } from "@/lib/api";
import { acknowledgeAlert, configureChannel } from "./actions";

export const dynamic = "force-dynamic";

export default async function AlertsPage() {
  let alerts: Alert[];
  let channels: AlertChannel[];
  try { [alerts, channels] = await Promise.all([apiGet<Alert[]>("/v1/alerts"), apiGet<AlertChannel[]>("/v1/alerts/channels")]); }
  catch (error) { return <ErrorState message={error instanceof Error ? error.message : "Alerts unavailable"} />; }
  return <><PageHeader eyebrow="Detection and response" title="Alerts" description="Explainable anomaly detections linked directly to the forensic timeline." /><div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Panel className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Open alerts</h2></div><div className="divide-y divide-slate-100">{alerts.length ? alerts.map((alert) => <article key={alert.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><SeverityBadge severity={alert.severity} /><span className="text-xs font-semibold text-slate-400">{humanize(alert.rule_id)}</span></div><h3 className="mt-3 font-semibold">{alert.title}</h3><p className="mt-1 text-sm text-slate-600">Agent {alert.agent_id} · observed {alert.hit_count}× · {formatDate(alert.last_seen)}</p></div><div className="flex gap-2"><Link href={`/sessions/${encodeURIComponent(alert.session_id)}#event-${alert.event_id}`} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Open replay</Link><form action={acknowledgeAlert.bind(null, alert.id)}><button className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold">Acknowledge</button></form></div></div>{alert.credential_ref ? <p className="mt-3 font-mono text-xs text-cyan-800">Credential {alert.credential_ref}</p> : null}</article>) : <p className="p-8 text-sm text-emerald-700">No open anomaly alerts.</p>}</div></Panel><div className="space-y-6"><Panel className="p-6"><h2 className="font-semibold">Delivery channels</h2><p className="mt-1 text-xs leading-5 text-slate-500">Provider secrets stay in deployment configuration and are never stored here.</p><div className="mt-5 space-y-3">{channels.map((channel) => <div key={`${channel.kind}-${channel.target}`} className="rounded-lg border border-slate-200 p-3"><b className="text-sm">{humanize(channel.kind)}</b><p className="mt-1 text-xs text-slate-500">{channel.target || "Configured channel"} · {channel.secret_configured ? "secret configured" : "deployment secret missing"}</p></div>)}</div><form action={configureChannel} className="mt-5 space-y-3"><select name="kind" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="slack">Slack</option><option value="email">Email</option></select><input name="target" type="email" placeholder="Email recipient (Slack leaves this blank)" className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-semibold text-white">Enable channel</button></form></Panel><Panel className="p-6"><h2 className="font-semibold">Cold-start safety</h2><p className="mt-2 text-sm leading-6 text-slate-600">Destructive actions and scope violations are active immediately. Volume spikes remain in learning mode until each agent has seven days of history.</p></Panel></div></div></>;
}
