import { ErrorState, PageHeader, Panel } from "@/components/ui";
import { apiGet, formatDate, humanize, type TenantSettings } from "@/lib/api";
import { revokeScopedToken, updateTenantSettings } from "./actions";
import { TokenForm } from "./token-form";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  let settings: TenantSettings;
  try { settings = await apiGet<TenantSettings>("/v1/settings"); }
  catch (error) { return <><PageHeader eyebrow="Workspace" title="Settings" description="Tenant identity, scoped tokens, retention, and non-disableable redaction controls." /><ErrorState message={error instanceof Error ? error.message : "Settings unavailable"} /></>; }
  const usagePercent = settings.usage.daily_event_plan_threshold
    ? Math.min(100, Math.round((settings.usage.events / settings.usage.daily_event_plan_threshold) * 100))
    : 0;
  return <>
    <PageHeader eyebrow="Workspace" title="Settings" description="Manage recording boundaries without weakening mandatory server-side redaction." />
    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <Panel className="p-6"><h2 className="font-semibold">Tenant and retention</h2><form action={updateTenantSettings} className="mt-5 space-y-4"><label className="block text-sm font-medium">Workspace name<input name="tenant_name" required maxLength={200} defaultValue={settings.tenant_name} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Payload retention (days)<input name="retention_days" required type="number" min={1} max={3650} defaultValue={settings.retention_days} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="flex items-start gap-3 rounded-lg bg-slate-50 p-4 text-sm"><input name="capture_payloads" type="checkbox" defaultChecked={settings.capture_payloads} className="mt-1" /><span><b>Store redacted payload bodies</b><span className="mt-1 block text-xs leading-5 text-slate-600">When disabled, metadata and a digest of the redacted body remain verifiable, but no payload body enters object storage.</span></span></label><button className="rounded-lg bg-[#081a2c] px-4 py-2 text-sm font-semibold text-white">Save settings</button></form></Panel>
      <Panel className="p-6"><h2 className="font-semibold">Members</h2><p className="mt-1 text-xs text-slate-500">Created {formatDate(settings.created_at)}</p><div className="mt-4 divide-y divide-slate-100">{settings.members.length ? settings.members.map((member) => <div key={member.user_ref} className="flex justify-between py-3 text-sm"><span className="font-mono text-xs">{member.user_ref}</span><span className="capitalize text-slate-500">{member.role}</span></div>) : <p className="py-3 text-sm text-slate-500">Local development workspace</p>}</div><h2 className="mt-6 font-semibold">Mandatory redaction rules</h2><div className="mt-3 flex flex-wrap gap-2">{settings.redaction_rules.map((rule) => <span key={rule} className="rounded-md bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-800">{humanize(rule)}</span>)}</div></Panel>
    </div>
    <Panel className="mt-6 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-600">{humanize(settings.plan_key)} plan</p><h2 className="mt-2 font-semibold">Aggregate daily events</h2><p className="mt-1 text-xs text-slate-500">Workspace usage for {settings.usage.day}. This plan threshold is reported separately from each recording token&apos;s protected payload allowance.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${settings.usage.plan_state === "over_plan" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{humanize(settings.usage.plan_state)}</span></div><div className="mt-5 flex items-end justify-between gap-4"><p className="text-3xl font-semibold tabular-nums">{settings.usage.events.toLocaleString()}<span className="text-base font-normal text-slate-500"> / {settings.usage.daily_event_plan_threshold?.toLocaleString() ?? "Unlimited"}</span></p>{settings.usage.remaining_plan_events !== null ? <p className="text-xs text-slate-500">{settings.usage.remaining_plan_events.toLocaleString()} plan events remaining</p> : null}</div>{settings.usage.daily_event_plan_threshold ? <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${settings.usage.plan_state === "over_plan" ? "bg-amber-500" : "bg-violet-600"}`} style={{ width: `${usagePercent}%` }} /></div> : null}</Panel>
    <Panel className="mt-6 p-6"><h2 className="font-semibold">Write-only tokens</h2><p className="mt-1 text-xs text-slate-500">Recording and scanner tokens are separately scoped. Values are shown once and stored only as hashes.</p><div className="mt-5"><TokenForm /></div><div className="mt-5 divide-y divide-slate-100">{settings.tokens.map((token) => { const revoke = revokeScopedToken.bind(null, token.kind, token.id); return <div key={`${token.kind}-${token.id}`} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{token.label}</p><p className="mt-1 text-xs text-slate-500">{humanize(token.kind)} · created {formatDate(token.created_at)}{token.revoked_at ? ` · revoked ${formatDate(token.revoked_at)}` : ""}{token.captured_payload_events_today !== null ? ` · ${token.captured_payload_events_today.toLocaleString()} / ${token.daily_payload_limit?.toLocaleString() ?? "Unlimited"} payloads today` : ""}</p></div><div className="flex items-center gap-3">{token.payload_allowance_state ? <span className={`text-xs font-semibold ${token.payload_allowance_state === "exhausted" ? "text-amber-700" : "text-slate-500"}`}>{humanize(token.payload_allowance_state)}</span> : null}{token.revoked_at ? <span className="text-xs font-semibold text-slate-400">Revoked</span> : <form action={revoke}><button className="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700">Revoke</button></form>}</div></div>; })}</div></Panel>
  </>;
}
