import { ErrorState, PageHeader, Panel } from "@/components/ui";
import { apiGet, formatDate, type InstallLink, type Integration } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function IntegrationsPage({ searchParams }: { searchParams: Promise<{ github?: string; org?: string }> }) {
  const status = await searchParams;
  let integrations: Integration[];
  let githubLink: InstallLink;
  try { [integrations, githubLink] = await Promise.all([apiGet<Integration[]>("/v1/dashboard/integrations"), apiGet<InstallLink>("/v1/integrations/github/install-url")]); }
  catch (error) { return <><PageHeader eyebrow="Connections" title="Integrations" description="Read-only provider connections and recording setup." /><ErrorState message={error instanceof Error ? error.message : "Unknown API error"} /></>; }
  const byProvider = Object.fromEntries(integrations.map((item) => [item.provider, item]));
  const awsTemplate = process.env.ABX_AWS_TEMPLATE_URL ?? "";
  const awsLink = awsTemplate ? `https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?templateURL=${encodeURIComponent(awsTemplate)}&stackName=AgentBlackBoxScanner` : "";
  return <>
    <PageHeader eyebrow="Connections" title="Integrations" description="Connect read-only scanner identities. Revocation credentials are intentionally separate and are never requested here." />
    {status.github === "connected" ? <div className="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">GitHub organization <b>{status.org}</b> connected. Its first read-only scan has been queued.</div> : null}
    <div className="grid gap-6 xl:grid-cols-2">
      <Panel className="overflow-hidden"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Amazon Web Services</p><h2 className="mt-2 text-xl font-semibold">AWS credential scanner</h2></div><Status connected={byProvider.aws?.connected} /></div><div className="p-6"><p className="text-sm leading-6 text-slate-600">Creates a cross-account role with AWS-managed SecurityAudit and ViewOnlyAccess policies plus ExternalId protection.</p><ScopeList items={["IAM users, roles, access keys and last-used data", "Policy reach and Access Advisor signals", "Zero write API permissions"]} /><p className="mt-5 text-xs text-slate-500">Last scan: {formatDate(byProvider.aws?.last_scan)}</p>{awsLink ? <a href={awsLink} className="mt-5 inline-flex rounded-lg bg-[#081a2c] px-4 py-2.5 text-sm font-semibold text-white">Open CloudFormation quick create</a> : <p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Set ABX_AWS_TEMPLATE_URL to enable the hosted CloudFormation quick-create link. Local scanning remains available through boto3 credentials.</p>}</div></Panel>
      <Panel className="overflow-hidden"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-600">GitHub</p><h2 className="mt-2 text-xl font-semibold">GitHub credential scanner</h2></div><Status connected={byProvider.github?.connected} /></div><div className="p-6"><p className="text-sm leading-6 text-slate-600">Install the read-only GitHub App to inventory fine-grained PATs, deploy keys, and App installations.</p><ScopeList items={["Personal access tokens: read", "Organization members and administration: read", "Repository metadata and deploy keys: read"]} /><div className="mt-5 rounded-lg border border-violet-200 bg-violet-50 p-3 text-xs leading-5 text-violet-900"><b>Visibility limit:</b> GitHub does not expose classic PATs through an organization API. We recommend blocking classic PAT access in organization policy.</div>{githubLink.configured && githubLink.install_url ? <a href={githubLink.install_url} className="mt-5 inline-flex rounded-lg bg-[#081a2c] px-4 py-2.5 text-sm font-semibold text-white">Install GitHub App</a> : <p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Set ABX_GITHUB_APP_SLUG, ABX_GITHUB_APP_ID, and ABX_GITHUB_PRIVATE_KEY to enable installation.</p>}</div></Panel>
    </div>
    <div className="mt-8"><h2 className="text-lg font-semibold">Recording sources</h2><p className="mt-1 text-sm text-slate-600">Capture setup included here for the onboarding path; deeper SDK instrumentation arrives in phase 5.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-cyan-700">MCP tap</p><h3 className="mt-2 font-semibold">Out-of-band tool recording</h3><pre className="mt-4 overflow-x-auto rounded-lg bg-slate-950 p-4 text-xs text-cyan-100">abx-tap install --client claude-code --agent my-agent</pre></Panel><Panel className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Python SDK · Phase 5</p><h3 className="mt-2 font-semibold">LangGraph and OTLP depth</h3><pre className="mt-4 overflow-x-auto rounded-lg bg-slate-100 p-4 text-xs text-slate-500">instrument(agent_id=&quot;my-agent&quot;)</pre></Panel></div></div>
  </>;
}

function Status({ connected }: { connected?: boolean }) { return <span className={`rounded-full px-3 py-1 text-xs font-bold ${connected ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{connected ? "Connected" : "Not connected"}</span>; }
function ScopeList({ items }: { items: string[] }) { return <ul className="mt-5 space-y-2">{items.map((item) => <li className="flex gap-2 text-xs text-slate-600" key={item}><span className="text-emerald-600">✓</span>{item}</li>)}</ul>; }
